modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker_url}"
clientSideOnly="${mod_client_side_only}"


[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="${mod_update_json_url}"
displayURL="${mod_display_url}"
logoFile="${mod_logo_file}"
credits="${mod_credits}"
authors="${mod_authors}"
displayTest="${mod_display_test}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

${mod_dependencies}